### ISSUE TITLE
No notarization for the plugin in MacOS Catalina.

### ISSUE THREAD

**Issue by Tony-83** [miyako/4d-plugin-gd#2]
Hello Keisuke,

Can you make an update for this plug-in to be Catalina friendly?

Thank you a lot!

**Comment by miyako** [comment]
I have rebuilt the libraries but I also want to update the main code to use native 4D objects instead of JSON, which will take some time.

**Comment by miyako** [comment]
new syntax here

https://miyako.github.io/2020/06/20/4d-plugin-gd-v2.html

**Comment by miyako** [comment]
done 

https://github.com/miyako/4d-plugin-gd-v2

**Comment by Tony-83** [comment]
Thank you very much, i'm gonna try it!
